// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCGuIXBhjXZqAV5jQcjdvY-6zzLa4BgTk',
    appId: '1:303180080421:web:f438f974c5132e0c52a6cc',
    messagingSenderId: '303180080421',
    projectId: 'banda-uni-app',
    authDomain: 'banda-uni-app.firebaseapp.com',
    storageBucket: 'banda-uni-app.firebasestorage.app',
    measurementId: 'G-KKPRBJ9NJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIDuRkGDt3ubSX1VNw2QVT1ow1coZ8AnA',
    appId: '1:303180080421:android:9acf7a03beae2d0752a6cc',
    messagingSenderId: '303180080421',
    projectId: 'banda-uni-app',
    storageBucket: 'banda-uni-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDziDiel2GG61kEcl_hqi_DGXzord-RAEw',
    appId: '1:303180080421:ios:6730c9a1bbf0954152a6cc',
    messagingSenderId: '303180080421',
    projectId: 'banda-uni-app',
    storageBucket: 'banda-uni-app.firebasestorage.app',
    iosBundleId: 'com.example.multiLocalizationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDziDiel2GG61kEcl_hqi_DGXzord-RAEw',
    appId: '1:303180080421:ios:6730c9a1bbf0954152a6cc',
    messagingSenderId: '303180080421',
    projectId: 'banda-uni-app',
    storageBucket: 'banda-uni-app.firebasestorage.app',
    iosBundleId: 'com.example.multiLocalizationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCGuIXBhjXZqAV5jQcjdvY-6zzLa4BgTk',
    appId: '1:303180080421:web:095af14c257bb75352a6cc',
    messagingSenderId: '303180080421',
    projectId: 'banda-uni-app',
    authDomain: 'banda-uni-app.firebaseapp.com',
    storageBucket: 'banda-uni-app.firebasestorage.app',
    measurementId: 'G-W64X2DV5KK',
  );
}
